### ISSUE TITLE
Node info doesn't show IPv4 connectivity

### ISSUE THREAD

**Issue by oitdmser** [Mirobit/bitcoin-node-manager#3]
Currently running my node with `onlynet=ipv4` and `listenonion=1`, so with active connections over TOR and clearnet, just not IPv6. The interface doesn't recognize the fact that IPv4 is active, it only notices the TOR.

Where does the script pull the IP and onion addresses from? Does it read the bind=x.x.x.x or externalip=x.x.x.x addresses in bitcoin.conf?

<img width="444" alt="Screen Shot 2019-05-24 at 6 32 41 AM" src="https://user-images.githubusercontent.com/44953598/58331341-c659b600-7ded-11e9-929b-bb6d7dce7a4d.png">

**Comment by oitdmser** [comment]
I tried specifying my current IP address to bitcoind using externalip=x.x.x.x when Bitcoin-Node-Manager loads, it is now able to see that I'm connected.

Here's the problem. Like most people I'm on a dynamic IP so I don't specify externalip= at the command line or in bitcoin.conf because it can change. Doesn't bitcoind automatically discover it's own IP? Can Bitcoin-Node-Manager use the IP address the bitcoind has auto-discovered?

**Comment by Mirobit** [comment]
Thanks for bringing this to my attention @oitdmser.

I will fix this bug as soon as possible.

**Comment by Mirobit** [comment]
https://github.com/Mirobit/bitcoin-node-manager/commit/0207d664c32741e3f4c8b4689d671dbc0b4dd170 Should fix this

**Comment by oitdmser** [comment]
Upgraded to v0.4 today and restarted apache. The problem I had still seems to exist. BNM still does not show the external ip address or even show that the node is reachable via ipv4.
![image](https://user-images.githubusercontent.com/44953598/76218400-6d6adb00-61d1-11ea-8ad1-6fae7df432b2.png)

**Comment by Mirobit** [comment]
Apparently your are not the only one where the IP info doesn't work (#5). Do you also have an active ipv6 and tor address?

**Comment by Mirobit** [comment]
a5c3785ed8d6a35868bc169f07e40e889087fd2e should finally fix this issue. I was not aware that the _localaddresses_ only works if some used the ip to connect to your node.

**Comment by oitdmser** [comment]
IPv4 connectivity is checked now. The only wrinkle is it doesn't show IP address, but in my research if `-externalip=x.x.x.x` isn't specified at the command line there isn't a good way to obtain external IP via bitcoind RPC calls. Something to think about for future features
